#!/bin/sh
# Tear down the Beep-Setup AP, re-enable the client STA, restore the normal LED
# ring. Called by the watchdog once the client connection is healthy again.
uci -q batch <<UCI
set wireless.setup.disabled=1
set wireless.@wifi-iface[0].disabled=0
commit wireless
UCI
uci -q del_list dhcp.@dnsmasq[0].address='/#/192.168.60.1'   # drop the DNS hijack
uci -q commit dhcp
rm -f /var/run/beep/led-mode                                 # leave AP-setup ring
wifi reload
/etc/init.d/dnsmasq restart 2>/dev/null
logger -t beep "wifi setup mode OFF; client STA re-enabled"
