#!/bin/sh /etc/rc.common
START=95
USE_PROCD=1
start_service() {
	local dev; dev="$(uci -q get beep.main.i2c_dev || echo /dev/i2c-0)"
	procd_open_instance
	procd_set_param command /usr/sbin/beepd "$dev"
	procd_set_param respawn 3600 5 5
	procd_set_param stdout 1; procd_set_param stderr 1
	procd_close_instance
}
